# Build settings
markdown: kramdown
sass:
  sass_dir: _sass

# Site settings
title: Sipho Hlophe
twitter_username: psyphore
name: Sipho Hlophe
firstname: Sipho
lastname: Hlophe
avatar_url: "https://avatars1.githubusercontent.com/u/4490427?s=460&u=6a92767cafa01d4bf05b76a2c7cb30b2d450db19&v=4"

#User specific content
#summary: ```[Family, Tech, Code, Learn, Teach, Fun]```
#Links that will appear in the navbar
primarylinks:
 - title: Email
   url: mailto:psyphore@gmail.com
   icon: fa fa-envelope fa-fw
 - title: GitHub
   url: https://github.com/psyphore
   icon: fa fa-github fa-fw
 - title: StackOverflow
   url: http://stackoverflow.com/users/1598285/psyphore
   icon: fa fa-stack-overflow fa-fw
 - title: LinkedIn
   url: https://www.linkedin.com/in/sipho-hlophe-8959ab34
   icon: fa fa-linkedin fa-fw
 - title: Twitter
   url: https://twitter.com/psyphore
   icon: fa fa-twitter fa-fw

#Any buzzword skills you want to include
skills:
 - C#.Net 7
 - ASP.Net MVC 5
 - .Net Core 3
 - GraphQL
 - REST
 - MSSQL
 - JavaScript ES5+
 - Neo4J
 - Cypher
 - Python 3
 - docker
 - Apollo (Server & Client)
 - Graphene
 - Unit Testing (NUnit, XUnit, Moq, NSubstitute)
 - GIT
 - XML
 - JSON
 - NodeJS
 - JIRA
 - Confluence
 - Assembla
 - Socket.IO
 - ReactJS
 - Angular
 - RAZOR3
 - TypeScript

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
# blogfeed: http://psyphore.github.io
 
#Work experience is required
roles:
  - title: Web Developer
    start: 2020
    end: ongoing
    employer: Better Life Group
    description: Fullstack developer at the financial sector
  - title: Web Developer
    start: 2018
    end: 2020
    employer: iPlatform Global
    description: Fullstack developer at the insurance sector
                frontend (KnockoutJS, RAZOR3, JavaScript ES5),
                backend (C#, ASP.Net MVC 4, NHibernate, .Net Core 2, Topshelf Apps),
                testing (XUnit, Moq),
                data (MSSQL, TSQL, XML, JSON),
                devOps (GIT with BitBucket, TeamCity, OctopusDeploy, IIS),
                docker (RabbitMQ),
                tech lead for 3rd party vendor integrations,
                coaching dev team with tools, techniques and processes (mostly through Confluence and workshops),
                release manager, orchestrating Sprint builds from Staging to Production,
                side quests (Python, ReactJS, GraphQL, Apollo, NodeJS, Neo4J [cypher], Google API, pm2, Node_alpine multi-stage docker builds).
  - title: Web Developer
    start: 2015
    end: 2017
    employer: Derivco
    description: Fullstack developer at a "Mixed bag" online entertainment sector
                frontend (AngularJS, Angular 2, NodeJS, TypeScript, JavaScript ES6),
                backend (C#, WebAPI, ASP.Net MVC 3, EF6-CodeFirst),
                testing (NUnit, NSubstitute),
                data (MSSQL, TSQL, JSON, XML),
                devOps (Git with GitLab, TeamCity, OctopusDeploy, IIS),
                coaching dev with tools, techniques and processes (mostly through Confluence),
                side quests (NodeJS, express, Angular 4, TypeScript, pm2, NGINX).
  - title: Web Developer
    start: 2013
    end: 2015
    employer: Hollywoodbets.net Sportbook
    description: Fullstack developer at a sportbook and betting sector 
                frontend (JQuery, KnockoutJS, AngularJS, JavaScript ES5),
                backend (ASP.Net, ASMX, C#, NHibernate),
                data (MSSQL, TSQL),
                devOps (Git with Mercurial, IIS).
  - title: Support Developer
    start: 2009
    end: 2013
    employer: Nedgroup Life
    description: Provide support to Business Information Server, Teleform and OnBase software, assist with system installation and queries, 
                Test system changes in all systems used within Nedgroup Life, 
                Produce data extracts and reports as required by the Business,
                Develop and implement business rules in VB & C#.Net in systems,
                Ensure that all systems are performing at top levels for smooth business operations,
                Perform Disaster Recovery procedures of systems during DR test sessions.
  - title: Desktop Support Engineer
    start: 2009
    end: 2009
    employer: Nedbank
    description: Help end-users in the organization with their computer related issues as soon as possible,
                Install new workstations for the end-users in the organization,
                Troubleshooting network issues for users.

#Education is required
education:
 - level: National Diploma in Information Technology
   date: 2007
   subject: Information Systems and Development Software
   school: Durban University of Technology

#List of interesting Github repo/projects to include - optional
github:
 - psyphore/media-streaming-server
 - psyphore/media-streaming-client
 - psyphore/flask-phone-book
 - psyphore/docker-composer
 - psyphore/graphql-neo4j-api
 - psyphore/react-apollo-client
 - psyphore/graphql-net_core-neo4j
 
bitbucket:
  - media-streaming-server
  - media-streaming-client

#Stackoverflow flair is optional
# stackoverflow:
#    profileurl: http://stackoverflow.com/users/1598285/psyphore
#    flairimageurl: http://stackoverflow.com/users/flair/1598285.png

introduction:
- I am a Full Stack Developer currently providing my skills and services at Better Life Group, in exchange, I'm learning about the home finance industry.
- Software development is my passion
- I enjoy creating great products with great user experiences and working in a dynamic environment with a focus on good development practices, automation and shipping small, frequent releases.
- Currently excited about the GRAND stack (GraphQL, ReactJS, Apollo, Neo4J Database) and everything GraphQL with Neo4J
- I have been also experimenting with Python3x version of the GRAND stack

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: 
- I love creating Software Solutions and learning how to better current Solutions with latest tech.
- I feel GraphQL is the future of APIs and a dream come true for system integrators and UI developers.
- Feel free to contact me on the mentioned links.

futureplans:
  - description: To have mastered the GraphQL concepts in different languages (NodeJS, Python, C#)
    progress: 70
    goal: GraphQL
  - description: To have re-written my media steaming server and client in Python and React
    progress: 0
    goal: React Streaming Solution
  - description: Strapi (with GraphQL) and Angular solution to manage the QA Cycle in a dev team or department
    progress: 0
    goal: Quality Assurance Management Solution

outro: Midrand, Gauteng, ZA
