# Site settings
title: Sipho Hlophe
twitter_username: psyphore
name: Sipho Hlophe

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/psyphore
 - title: StackOverflow
   url: http://stackoverflow.com/users/1598285/psyphore
 - title: LinkedIn
   url: https://www.linkedin.com/in/sipho-hlophe-8959ab34

#Any buzzword skills you want to include
skills:
 - C#.Net
 - ASP.Net MVC
 - REST
 - SQL
 - Java
 
#Work experience is required
roles:
- title: Junior Web Developer
   start: 2015
   end: ongoing
   employer: Derivco
   description: do some shit
- title: Junior Software Developer
   start: 2013
   end: 2015
   employer: Hollywoodbets.net Sportbook
   description: do some shit
- title: Support Developer
   start: 2010
   end: 2013
   employer: Nedgroup Life Assurance
   description: do some shit
 - title: Desktop Support Engineer
   start: 2009
   end: 2010
   employer: Nedbank
   description: do some shit

#Education is required
education:
 - level: National Diploma in Information Technology
   date: 2007
   subject: Information Systems and Development Software
   school: Durban University of Technology

#List of interesting Github repo/projects to include - optional
github:
 - psyphore/psyphore.github.io
 
#Stackoverflow flair is optional
stackoverflow:
   profileurl: http://stackoverflow.com/users/1598285/psyphore
   flairimageurl: http://stackoverflow.com/users/flair/1598285.png

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>General</strong>: I love creating Software Solutions and learning how to better current Solutions with latest tech.
