# Site settings
title: Sipho Hlophe
twitter_username: psyphore
name: Sipho Hlophe

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/psyphore
 - title: StackOverflow
   url: http://stackoverflow.com/users/1598285/psyphore
 - title: LinkedIn
   url: https://www.linkedin.com/in/sipho-hlophe-8959ab34

#Any buzzword skills you want to include
skills:
 - C#.Net
 - ASP.Net MVC
 - REST
 - SQL
 - Java

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: http://psyphore.github.io
 
#Work experience is required
roles:
- title: Junior Web Developer
  start: 2015
  end: Ongoing
  employer: Derivco
  description: Create and maintain business solutions using SQL (T-SQL, DB Design), C#, ASP.Net Web API 2, Angular.js 1.x, Angular 2, Bootstrap 3, HTML5, Node.js, Grunt and Gulp.js
- title: Junior Software Developer
  start: 2013
  end: 2015
  employer: Hollywoodbets.net Sportbook
  description: Create Business Solutions using C#.NET 4.5, SQL (T-SQL), ASP.NET (MVC 5 & Web API 2), HTML 5, CSS 3, JQuery & Angular.js
- title: Support Developer
  start: 2009
  end: 2013
  employer: Nedgroup Life Assurance
  description: Provide support to Business Information Server, Teleform and OnBase software, assist with system installation and queries, 
               Test system changes in all systems used within Nedgroup Life, 
               Produce data extracts and reports as required by the Business,
               Develop and implement business rules in VB & C#.Net in systems,
               Ensure that all systems are performing at top levels for smooth business operations,
               Perform Disaster Recovery procedures of systems during DR test sessions.
- title: Desktop Support Engineer
  start: 2009
  end: 2009
  employer: Nedbank
  description: Help end-users in the organization with their computer related issues as soon as possible,
               Install new workstations for the end-users in the organization,
               Troubleshooting network issues for users.

#Education is required
education:
 - level: National Diploma in Information Technology
   date: 2007
   subject: Information Systems and Development Software
   school: Durban University of Technology

#List of interesting Github repo/projects to include - optional
github:
 - psyphore/psyphore.github.io
 
#Stackoverflow flair is optional
stackoverflow:
   profileurl: http://stackoverflow.com/users/1598285/psyphore
   flairimageurl: http://stackoverflow.com/users/flair/1598285.png

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>General</strong>: I love creating Software Solutions and learning how to better current Solutions with latest tech.
